<a href="https://colab.research.google.com/github/ShreyaaChauhan/code/blob/master/Assignment7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1** Write a function so that the columns of the output matrix are powers of the input
vector.

**Sol** 

In [74]:
import numpy as np
a = input("enter the list separated by comma\n")
l = a.split(',')

new_list = [int(i) for i in l]
print("Entered vector is ",new_list) 

def function_vander(l,new_list):
  final_list =[[x**i for i in range(0,len(l))] for x in new_list]
  final_matrix = np.mat(final_list)
  print("vander matrix is \n ",np.flip(final_matrix, axis=1))

function_vander(l,new_list)




enter the list separated by comma
1,2,3
Entered vector is  [1, 2, 3]
vander matrix is 
  [[1 1 1]
 [4 2 1]
 [9 3 1]]


**Inbuilt Vander function in numpy**

In [68]:
x = np.array([1, 2, 3,4])
N = 4
np.vander(x, N)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

**2** Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

**Sol**

**When list and window are given/specified**

In [119]:
l = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
y=[]
for i in range(0,len(l)-2):
  y.append(int((l[i]+l[i+1]+l[i+2])/3))

print("moving average in an array over a window is :",y)

moving average in an array over a window is : [5, 4, 5, 6, 9, 28, 49, 72, 84, 93, 116]


**When list and window are taken  by user**

In [120]:
list = input("Enter list seperated by commas")
window = int(input("Enter window size"))
c = list.split(',')
l = [ int(i) for i in c]

def Window_sum(list,window):
  sum = []
  for i in range(0,len(list)-(window-1)):
    a = 0
    for i in range(i,i+window):
      a = a + list[i]
    sum.append(int(a/window))
  print("moving average in an array over a window is:",sum)
  
Window_sum(l,window)

Enter list seperated by commas1,2,3,4,5,6,7,8,9,10
Enter window size3
moving average in an array over a window is: [2, 3, 4, 5, 6, 7, 8, 9]
